# kubectl -n tekton apply -f github-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: tekton
stringData:
  token: <GitHub Private Token>
  secret: <Random String for Webhook Secret>
data:
  id_rsa: <base64 encode of Private Key> # The public key must be uploaded to GitHub
  
  # Host github.com
  # HostName github.com
  # StrictHostKeyChecking no
  config: <base64 encode of SSH Config>
