# kubectl -n tekton apply -f registry-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
data:
  config.json: <base64 encode docker auth> # see: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/